export const UserRole = {
  ADMIN: "ADMIN",
  DRIVER: "DRIVER",
  CUSTOMER: "CUSTOMER",
  EMPLOYEE: "EMPLOYEE",
  CONTRACTS_MANAGER: "CONTRACTS_MANAGER",
  ALLOCATIONS_MANAGER: "ALLOCATIONS_MANAGER",
  HUMAN_RESOURCES_MANAGER: "HUMAN_RESOURCES_MANAGER"
} as const;

export type UserRole = (typeof UserRole) [keyof typeof UserRole];